### ISSUE TITLE
How to use a nix-managed docker image in arion

### ISSUE THREAD

**Issue by cameron1024** [hercules-ci/arion#169]
I'm quite new to Nix, so this might just be my inability to read the docs properly, apologies in advance.

I have a `flake.nix` that defines an output which is a docker image built with `pkgs.dockerTools.buildImage`. I'd like to deploy this using arion. Using docker-compose, I'd write something like this as my `docker-compose.yml`:
```yml
version: "3.9"
services:
  web:
    depends_on: ["db"]
    build: .
    ports:
      - "8000:8000"
  db:
    image: "postgres"
```
Currently, my best attempt at a `arion-compose.yml` is the following:
```nix
{
  services.db = {
      service.image = "postgres";
      service.volumes = [ "${toString ./.}/postgres-data:/var/lib/postgresql/data" ];
      service.environment.POSTGRES_PASSWORD = "password";
  };

  services.backend = {
    service.depends_on = [ "db" ];
    service.build = "???";
  };
}
```

I'm not sure how to get the image built inside my flake into the `backend` service. Any advice is much appreciated :grin:
